<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10</LangVersion>
		<ApplicationDefaultFont>Segoe UI, 9pt</ApplicationDefaultFont>
		<PublishSingleFile>true</PublishSingleFile>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>false</SelfContained>
		<ApplicationIcon>MergerIcon256.ico</ApplicationIcon>
		<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
		<AssemblyName>TXTFilesMerger</AssemblyName>
		<Product>TXTFilesMerger</Product>
		<AssemblyTitle>TXTFilesMerger</AssemblyTitle>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="MergerIcon256.ico" />
	</ItemGroup>
</Project>